Data <- read.csv("/home/dhanalaxmi/Desktop/contribution/sensor.csv")
Data<-as.data.frame(Data)
DF<-(lm(TOR_PER ~ CURRENT+POWER+RPM+MP+TOR_NM,data=Data))
print(DF)
uni_1<-(lm(TOR_PER ~POWER+RPM+MP+TOR_NM, data=Data))
uni_2<-(lm(TOR_PER ~CURRENT+RPM+MP+TOR_NM, data=Data))
uni_3<-(lm(TOR_PER ~CURRENT+POWER+MP+TOR_NM, data=Data))
uni_4<-(lm(TOR_PER ~CURRENT+POWER+RPM+TOR_NM, data=Data))
uni_5<-(lm(TOR_PER ~CURRENT+POWER+RPM+MP, data=Data))
ori_R_squ<-((summary(DF)$r.square))
a_R_squ<-((summary(uni_1)$r.square))
b_R_squ<-((summary(uni_2)$r.square))
c_R_squ<-((summary(uni_3)$r.square))
d_R_squ<-((summary(uni_4)$r.square))
e_R_squ<-((summary(uni_5)$r.square))
a_val<-((ori_R_squ)-(a_R_squ))
b_val<-((ori_R_squ)-(b_R_squ))
c_val<-((ori_R_squ)-(c_R_squ))
d_val<-((ori_R_squ)-(d_R_squ))
e_val<-((ori_R_squ)-(e_R_squ))
print(paste("Total Regression : ",ori_R_squ))
print(paste("CURRENT: ",a_R_squ))
print(paste("POWER: ", b_R_squ))
print(paste("RPM: ",c_R_squ))
print(paste("MP: ",d_R_squ))
print(paste("TOR_NM: ",e_R_squ))
Rank<-rank(-(c(a_val,b_val,c_val,d_val,e_val)))
print(Rank)

